### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by luffyxxsenpai** [ray-pH/polybar-cava#2]
any idea how can we customize colors and bar widh

**Comment by ray-pH** [comment]
Overall color can be changed by editing your polybar config
```
[module/cava]
label-foreground = #594751
```
Editing color for each bar is a little bit tricky, but can be done. Do you think about different coloros for each bar (different color horizontally), or different color for each level?
I think having different color for each level of height will be weird though, and you can't really have a color gradient vertically since each bar is essentially just a single character.
