### ISSUE TITLE
Anyway to pull config settings from the standard cava config?

### ISSUE THREAD

**Issue by Ishmael-Lewis** [ray-pH/polybar-cava#3]
I was looking to add elememts from my standard cava config like gradient, sensitivity, and frequency domains, but it seems simply copying these things from my standard config to the polybar cava config doesnt seem to work. 

Is there any way this is possible to incorporate these values to the polybar cava config?

**Comment by ray-pH** [comment]
Color gradient is not really possible since each bar is just a single character. Other configs such as sensitivity and frequency domains should still work just fine, just put your config inside the cava config portion in the `cava.sh` file
```
[general]
bars = 10

[output]
method = raw
raw_target = $pipe
data_format = ascii
ascii_max_range = 7
```
Edit your config in that region

Just remember that there's only 7 possible height of the bar, so small change in sensirivity might not be that visible

If you happen to have font that support more height level or simply want to change the bars into other characters, you can always change the variable `bar` into list of bars that you wan't to use, for example
```
bar="._▁▂▃▄▅▆▇█"
```
and change the `ascii_max_range` into the number of char that you provide in `bar`
```
ascii_max_range = 10
```

**Comment by Ishmael-Lewis** [comment]
so even components such as setting a particular source should work in theory yes? as long as i port it to the cava.sh file? Is the syntax different in this regard or can I port things one to one like 

[input]
method = pulse
source = auto

**Comment by Ishmael-Lewis** [comment]
I ask this as I recently got a new microphone and for some reason after each polybar reboot the cava module seems to default to the monitor of said microphone, and there seems to be no way in pavucontrol to inhibit the cava module from pulling from the microphone sink every reboot, so perhaps is there a way to set it manually in the .sh script? so far what ive tried from porting my standard cava config has not seemed to solve the issue

**Comment by ray-pH** [comment]
In theory, yes. All cava config that's not related to how the bar is displayed should still works.
The only canva config that the program require is the `[output]` part
```
[output]
method = raw
raw_target = $pipe
data_format = ascii
ascii_max_range = 7
```
Other than that, you can change it to whatever you want

You can actually run `cava.sh` on it's own without polybar and try to debug your problem from there
```
$ bash cava.sh
```

The generated config file is also stored in `/tmp/polybar_cava_config`, you can check there to see wether the generated config is correct or not
```
$ cat /tmp/polybar_cava_config
```
